### ISSUE TITLE
[FE] Paragraph sign is used as a text for link at <h1>, <h2>, <h3>..

### ISSUE THREAD

**Issue by atsiatserkina** [qgis/QGIS-Hugo#201]
Environment:
Operation system with version - macOS 13.0 Browser with version - Google Chrome Version 121.0.6167.160 (Official Build) (arm64)General link (main page of application) / version - https://qgis.github.io/QGIS-Hugo/download/

Steps:
Open https://qgis.github.io/QGIS-Hugo/resources/installation-guide/#osgeo4w-installer
Scroll to <h> tags and try to click the link Result:
Paragraph sign is used as a text for link at `<h1>, <h2>, <h3>.` 

![Image](https://github.com/qgis/QGIS-Hugo/assets/90207604/c9218db6-d35a-41fa-b94e-cfea134c6355)

![Image](https://github.com/qgis/QGIS-Hugo/assets/90207604/387a9f83-a826-4bca-ab08-29575c0565de)

Expected Result:
Link should be on the text of the <h> tag, not on paragraph sign
Need to fix css/js, as just `<h3 id="quickstart"><a class="heading-anchor" href="#quickstart">Quickstart</a></h3>`
creates text that appears only when navigating to it

Affected Areas:
UI

**Comment by timlinux** [comment]
This is maybe a feature, I dont know what the original design intent was. For me it is ok to keep it like this for now.
