### ISSUE TITLE
Closing donation "nagscreen" leaves download page in confusing, scrolled-down state

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS-Hugo#325]
### URL

https://qgis.org/download/

### On what type of device(s) did you see this bug?

Phone, Desktop

### On which browser(s) are you seeing the problem?

Firefox

### Summary

The "Before download starts" text is long so a user might often have to scroll down to click the "Skip it and go to download" button.

Afterwards, the actual downloads page is in a scrolled-down state, which is confusing to the user.

I think the button should make the message disappear *and* scroll up if that is possible.

# Example
![image](https://github.com/qgis/QGIS-Hugo/assets/7661092/2fd6dff5-250e-4f9b-9d80-2c5235a2be10)

Having to scroll down to close the message:
![image](https://github.com/qgis/QGIS-Hugo/assets/7661092/5c50ef52-b5ce-4403-b06c-477439d90e94)

Resulting Downloads page:
![image](https://github.com/qgis/QGIS-Hugo/assets/7661092/411dd89a-3ce3-4da3-b29c-c43a71e4bf1a)

# Wanted state of Downloads page
![image](https://github.com/qgis/QGIS-Hugo/assets/7661092/2780d64a-8c87-4b85-b989-0d02938deb94)

**Comment by Xpirix** [comment]
Thanks for the suggestion @kannes , this has been fixed. I'm closing it.

**Comment by kannes** [comment]
Works well, thank you!
