### ISSUE TITLE
Old changelog URLs need a redirect

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS-Hugo#326]
### URL

https://qgis.org/en/site/forusers/visualchangelog338/

### Summary

https://qgis.org/en/site/forusers/visualchangelog338/ is getting directed to https://qgis.org/

Should redirect to https://qgis.org/project/visual-changelogs/visualchangelog338/ instead.

**Comment by Xpirix** [comment]
This issue has been fixed. I am closing it.
