### ISSUE TITLE
Cannot access QGIS Python (PyQGIS) API

### ISSUE THREAD

**Issue by SGroe** [qgis/QGIS-Hugo#333]
### URL

https://qgis.org/pyqgis/3.34/

### On what type of device(s) did you see this bug?

Desktop

### On which browser(s) are you seeing the problem?

Microsoft Edge

### Summary

I cannot reach https://qgis.org/pyqgis/3.34/ or https://qgis.org/pyqgis/master/

**Comment by SGroe** [comment]
Links on the following pages point to a "404 - There isn't a GitHub Pages site here."

- https://qgis.org/resources/hub/
- https://docs.qgis.org/3.34/en/docs/pyqgis_developer_cookbook/cheat_sheet.html#sources

**Comment by kannes** [comment]
As a workaround you can try if the Internet Archive has the wanted pages archived. Start from http://web.archive.org/web/20240427104917/https://qgis.org/pyqgis/3.34/

**Comment by kannes** [comment]
A better workaround is this:
You can download zip releases of the docs at https://github.com/qgis/pyqgis-api-docs-builder/releases
E. g. https://github.com/qgis/pyqgis-api-docs-builder/releases/tag/3.38 -> https://github.com/qgis/pyqgis-api-docs-builder/releases/download/3.38/pyqgis-docs-3.38.zip

Extract that and open the `build/index.html` file in your web browser as entry point.

**Comment by kannes** [comment]
Seems to be caused by https://github.com/qgis/pyqgis-api-docs-builder/issues/125#issuecomment-2223279243

**Comment by Xpirix** [comment]
Hi everyone, please also see my comment there. https://github.com/qgis/pyqgis-api-docs-builder/issues/125#issuecomment-2225064102.

**Comment by Xpirix** [comment]
The issue has been fixed. Thanks to @3nids.

**Comment by agiudiceandrea** [comment]
@kannes @Xpirix please see https://github.com/qgis/QGIS-Hugo/issues/343.
