### ISSUE TITLE
PyQGIS QGIS Python API docs are not properly formatted

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Hugo#343]
### URL

https://qgis.org/pyqgis/master/

### Type(s) of Problems

Other

### Summary

https://qgis.org/pyqgis/master/

![image](https://github.com/user-attachments/assets/268958ca-506e-4a57-a6ec-ed10c8d3aa34)

https://qgis.org/pyqgis/3,34/

![image](https://github.com/user-attachments/assets/0e6d1112-829b-4ca8-827d-53d387c91069)

**Comment by Xpirix** [comment]
Thanks for reporting @agiudiceandrea, it has been fixed. It might require clearing the cache.
