### ISSUE TITLE
"Download" button and menu item don't work: https://www.qgis.org/download/ 301 Moved permanently

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Hugo#348]
### URL

www.qgis.org

### On what type of device(s) did you see this bug?

Desktop

### On which browser(s) are you seeing the problem?

Chrome

### Summary

Using Chrome 126.0.6478.127 on Windows 10 64-bit, the Download button and the Download menu item on the main page don't work.

They are linked to https://www.qgis.org/download/ while the server replays with "Status Code: `301 Moved Permanently`" and "Location: `https://www.qgis.org/`".

**Comment by timlinux** [comment]
This should be working now - we had some issues during deployment. Thanks.
