### ISSUE TITLE
404 on schedule.ics link

### ISSUE THREAD

**Issue by landryb** [qgis/QGIS-Hugo#356]
### Summary

https://qgis.org/schedule.ics is linked from https://www.qgis.org/resources/roadmap/ but is a 404.

it is a pretty useful feature to know when the next release is planned, i used the ics from thunderbird.

**Comment by sebastic** [comment]
I likewise use schedule.ics in Thunderbird to know when new QGIS releases are planned for which I need to update the Debian package. I was surprised to see yesterdays release as it wasn't in my calendar.
